import LegalPage from "@/app/components/LegalPage";

export default function TermsPage(){return <LegalPage eyebrow="Informações legais" title="Termos de Uso" intro="Estes Termos explicam as regras para utilizar a Cosmic Store e contratar nossos produtos digitais. Ao criar uma conta ou realizar um pedido, você declara que leu e concorda com estas condições.">
  <section><h2>1. Sobre a Cosmic Store</h2><p>A Cosmic Store comercializa produtos e benefícios digitais relacionados a jogos. A loja é independente e não representa, patrocina ou mantém vínculo oficial com Roblox, Discord ou com os desenvolvedores dos jogos anunciados, salvo quando informado expressamente.</p></section>
  <section><h2>2. Conta e segurança</h2><p>O cliente deve fornecer informações verdadeiras, manter a conta protegida e utilizar um e-mail ou Discord ao qual tenha acesso. Nunca solicitamos a senha da conta do jogo. O uso por menores deve ocorrer com conhecimento e autorização de seu responsável legal.</p></section>
  <section><h2>3. Pedido e pagamento</h2><p>O preço, a quantidade e o produto são apresentados antes da finalização. O Pix é conferido manualmente; o envio do comprovante não significa aprovação imediata. O pedido somente é considerado pago quando a equipe marcar o pagamento como confirmado.</p><p>Comprovantes ilegíveis, incompatíveis com o valor, duplicados, adulterados ou que não correspondam a um crédito efetivamente recebido podem ser recusados. Nesse caso, o motivo será exibido e o cliente poderá enviar um novo arquivo.</p></section>
  <section><h2>4. Entrega em até 24 horas</h2><p>Após a confirmação do pagamento, a Cosmic Store realizará a entrega em até 24 horas. O prazo e sua data-limite ficam disponíveis na página do pedido.</p><p>O prazo poderá ficar suspenso enquanto houver impedimento causado por informação incorreta, ausência de cooperação do cliente, indisponibilidade da plataforma do jogo, manutenção externa, bloqueio da conta ou evento fora do controle razoável da loja. A equipe informará o cliente pelo atendimento sempre que possível.</p></section>
  <section><h2>5. Responsabilidade do cliente</h2><ul><li>Informar corretamente o nickname e demais dados necessários à entrega.</li><li>Manter a conta apta a receber o produto.</li><li>Acompanhar as notificações e responder ao chat do pedido.</li><li>Não enviar comprovante falso, adulterado ou pertencente a pagamento estornado.</li><li>Conferir a descrição e a compatibilidade do produto antes de comprar.</li></ul></section>
  <section><h2>6. Atendimento</h2><p>O chat privado é liberado após a confirmação do pagamento. Quando o pedido for entregue, o atendimento poderá ser encerrado, preservando o histórico. A equipe poderá reabri-lo quando necessário. O chat global deve ser utilizado com respeito; spam, fraude, assédio, discurso de ódio e exposição de dados pessoais podem resultar em remoção de conteúdo ou bloqueio.</p></section>
  <section><h2>7. Cancelamentos e reembolsos</h2><p>As regras completas estão na Política de Reembolso. Nenhuma disposição destes Termos elimina direitos garantidos pela legislação brasileira de proteção ao consumidor.</p></section>
  <section><h2>8. Disponibilidade e alterações</h2><p>Podemos realizar manutenções, corrigir erros e atualizar funcionalidades, preços ou estes Termos. Alterações relevantes serão apresentadas de forma clara e não reduzirão direitos relativos a pedidos já confirmados.</p></section>
  <section><h2>9. Contato</h2><p>Dúvidas sobre pedidos devem ser enviadas pelo chat privado ou pelos canais de suporte exibidos no site. Informe o código do pedido, mas nunca envie senhas.</p></section>
</LegalPage>}
