"use client";
import {FormEvent,useCallback,useEffect,useRef,useState} from "react";import {createClient} from "@/lib/supabase/client";
type Message={id:string;user_id:string;message:string;created_at:string;profiles?:{nickname:string;avatar_url:string|null}|null};
export default function OrderChat({orderId,userId,initialMessages,canSend=true}:{orderId:string;userId:string;initialMessages:Message[];canSend?:boolean}){
 const [messages,setMessages]=useState(initialMessages);const [message,setMessage]=useState("");const [error,setError]=useState("");const listRef=useRef<HTMLDivElement>(null);const keepAtBottom=useRef(true);const subscribedRef=useRef(false);
 const refresh=useCallback(async()=>{const {data}=await createClient().from("order_messages").select("id,user_id,message,created_at,profiles(nickname,avatar_url)").eq("order_id",orderId).order("created_at");if(data){const next=data as unknown as Message[];setMessages(current=>current.length===next.length&&current.every((item,index)=>item.id===next[index]?.id&&item.message===next[index]?.message)?current:next);}},[orderId]);
 useEffect(()=>{const supabase=createClient();const channel=supabase.channel(`order-chat-${orderId}`).on("postgres_changes",{event:"*",schema:"public",table:"order_messages",filter:`order_id=eq.${orderId}`},()=>void refresh()).subscribe(status=>{subscribedRef.current=status==="SUBSCRIBED";});const interval=window.setInterval(()=>{if(!subscribedRef.current&&document.visibilityState==="visible")void refresh();},15000);const sync=()=>{if(document.visibilityState==="visible")void refresh();};window.addEventListener("focus",sync);document.addEventListener("visibilitychange",sync);return()=>{window.clearInterval(interval);window.removeEventListener("focus",sync);document.removeEventListener("visibilitychange",sync);void supabase.removeChannel(channel);};},[orderId,refresh]);
 useEffect(()=>{if(keepAtBottom.current&&listRef.current)listRef.current.scrollTo({top:listRef.current.scrollHeight,behavior:"smooth"});},[messages]);
 async function send(event:FormEvent){event.preventDefault();const clean=message.trim();if(!clean)return;keepAtBottom.current=true;setError("");setMessage("");const tempId=`temp-${Date.now()}`;setMessages(current=>[...current,{id:tempId,user_id:userId,message:clean,created_at:new Date().toISOString(),profiles:null}]);const response=await fetch(`/api/orders/${orderId}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:clean})});const data=await response.json();if(!response.ok){setMessages(current=>current.filter(item=>item.id!==tempId));setMessage(clean);setError(data.error??"Não foi possível enviar.");return;}await refresh();}
 return <section className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-[#121017]"><div className="border-b border-white/10 p-5"><h2 className="font-black">Conversa do pedido</h2><p className="mt-1 text-xs text-zinc-500">Somente você e a equipe da Cosmic Store podem ver.</p></div><div ref={listRef} onScroll={event=>{const element=event.currentTarget;keepAtBottom.current=element.scrollHeight-element.scrollTop-element.clientHeight<80;}} className="h-[360px] space-y-3 overflow-y-auto p-5">{messages.length?messages.map(item=><div key={item.id} className={`flex ${item.user_id===userId?"justify-end":"justify-start"} ${item.id.startsWith("temp-")?"opacity-70":""}`}><div className={`max-w-[80%] rounded-2xl px-4 py-3 ${item.user_id===userId?"bg-violet-600":"bg-white/5"}`}><p className="mb-1 text-xs font-bold opacity-70">{item.profiles?.nickname??(item.user_id===userId?"Você":"Equipe")}</p><p className="whitespace-pre-wrap text-sm">{item.message}</p><time className="mt-1 block text-[10px] opacity-50">{item.id.startsWith("temp-")?"enviando...":new Date(item.created_at).toLocaleString("pt-BR")}</time></div></div>):<p className="text-center text-sm text-zinc-500">Nenhuma mensagem neste atendimento.</p>}</div>{canSend?<form onSubmit={send} className="flex gap-2 border-t border-white/10 p-4"><input value={message} onChange={e=>setMessage(e.target.value)} maxLength={1000} placeholder="Digite sua mensagem..." className="min-w-0 flex-1 rounded-xl border border-white/10 bg-[#08070b] px-4 py-3 outline-none focus:border-violet-500"/><button className="rounded-xl bg-violet-600 px-5 font-bold">Enviar</button></form>:<div className="border-t border-white/10 bg-white/[.02] p-4 text-center text-sm text-zinc-400"><strong className="text-zinc-200">Atendimento encerrado.</strong> O histórico continua disponível. A equipe pode reabrir este chat se necessário.</div>}{error&&<p className="px-4 pb-4 text-xs text-red-300">{error}</p>}</section>;
}
