import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import SiteHeader from "@/app/components/SiteHeader";
import SiteFooter from "@/app/components/SiteFooter";
import AddToCartButton from "@/app/components/AddToCartButton";
import StoreFeedbacks from "@/app/components/StoreFeedbacks";
import { createClient } from "@/lib/supabase/server";
import { withSignedReviewAttachments } from "@/lib/review-attachments";
export const dynamic = "force-dynamic";
export default async function ProductDetail({ params }: { params: Promise<{slug:string}> }) {
  const {slug}=await params;const client=await createClient();
  const [{data:product},{data:feedbacks}]=await Promise.all([client.from("products").select("id,name,slug,description,price,image_url,stock,unlimited_stock,is_active").eq("slug",slug).eq("is_active",true).single(),client.from("feedbacks").select("id,rating,comment,author_nickname,created_at,source,attachment_path").eq("is_visible",true).order("created_at",{ascending:false}).limit(3)]);
  if(!product)notFound();
  const signedFeedbacks=await withSignedReviewAttachments(feedbacks??[]);
  const soldOut = !product.unlimited_stock && product.stock <= 0;
  return <div className="min-h-screen"><SiteHeader/><main className="shell py-8 md:py-12"><nav aria-label="Navegação de localização" className="mb-6 flex flex-wrap items-center gap-2 text-xs text-zinc-500"><Link href="/">Início</Link><span>/</span><Link href="/produtos">Produtos</Link><span>/</span><span className="text-zinc-200">{product.name}</span></nav><div className="grid items-start gap-7 lg:grid-cols-[1fr_.9fr] lg:gap-12"><div className="product-detail-art relative aspect-square overflow-hidden rounded-2xl border border-white/10"><Image src={product.image_url || "/images/products/placeholder.svg"} alt={product.name} fill priority sizes="(max-width:1024px) 100vw,50vw" className="object-contain p-8 md:p-14" /></div><div className="lg:pt-4"><span className="inline-flex rounded-full border border-violet-400/20 bg-violet-500/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-wider text-violet-200">ITEM DIGITAL</span><h1 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl lg:text-5xl">{product.name}</h1><div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-zinc-400"><span className={soldOut ? "text-amber-300" : "text-emerald-300"}>● {soldOut ? "Esgotado" : "Disponível"}</span><span>Pagamento via Pix</span><span>Suporte no site</span></div><p className="mt-6 whitespace-pre-line text-sm leading-7 text-zinc-400 sm:text-base">{product.description || "Item digital para o seu jogo. Consulte a equipe se tiver dúvidas antes de comprar."}</p><div className="mt-8 rounded-xl border border-white/10 bg-[#17121f] p-5 sm:p-6"><p className="text-xs font-semibold uppercase tracking-wider text-zinc-400">Valor do item</p><strong className="mt-2 block text-3xl font-black tracking-tight sm:text-4xl">{Number(product.price).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</strong><p className="mt-2 text-xs text-zinc-500">{product.unlimited_stock ? "Estoque ilimitado" : `${product.stock} unidades disponíveis`}</p><div className="mt-6"><AddToCartButton produto={product}/></div><Link href="/carrinho" className="btn-secondary mt-3 w-full">Ir para o carrinho →</Link></div><div className="mt-5 rounded-xl border border-white/[.075] p-4 text-xs leading-6 text-zinc-400"><strong className="block text-sm text-white">Como funciona?</strong><p className="mt-1">Adicione ao carrinho, informe seu nickname no checkout, pague via Pix e envie o comprovante. A equipe confirma o pagamento antes da entrega.</p><Link href="/suporte" className="mt-2 inline-block font-bold text-violet-300">Precisa de ajuda? ↗</Link></div></div></div></main><section className="border-t border-white/[.07] py-10"><StoreFeedbacks feedbacks={signedFeedbacks}/></section><SiteFooter/></div>;
}
