"use client";
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { useCart } from "@/app/context/CartContext";

export default function CartContent() {
  const { items, removeFromCart, updateQuantity, clearCart } = useCart();
  const total = items.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
  return <main className="shell py-10 md:py-14"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-400">Seu pedido</p><h1 className="mt-2 text-4xl font-black">Carrinho</h1></div><span className="text-sm text-zinc-500">{items.reduce((sum,item)=>sum+item.quantity,0)} itens</span></div>{items.length?<div className="mt-8 grid gap-7 lg:grid-cols-[1fr_360px]"><div className="space-y-3">{items.map(item=><div key={item.id} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-[#121017] p-4"><div className="grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-xl bg-violet-500/10">{item.image_url?<img src={item.image_url} alt="" className="h-full w-full object-contain p-2"/>:<span className="text-3xl">✦</span>}</div><div className="min-w-0 flex-1"><h2 className="truncate font-bold">{item.name}</h2><strong className="mt-2 block">{money(item.price)}</strong></div><div className="flex items-center rounded-xl border border-white/10"><button aria-label="Diminuir" onClick={()=>updateQuantity(item.id,item.quantity-1)} className="p-2.5">−</button><span className="min-w-7 text-center text-sm font-bold">{item.quantity}</span><button aria-label="Aumentar" onClick={()=>updateQuantity(item.id,item.quantity+1)} className="p-2.5">+</button></div><button onClick={()=>removeFromCart(item.id)} className="p-2 text-sm text-zinc-500 hover:text-red-400">Remover</button></div>)}</div><aside className="h-fit rounded-2xl border border-white/10 bg-[#121017] p-6"><h2 className="text-xl font-black">Resumo</h2><div className="mt-6 flex justify-between text-zinc-400"><span>Subtotal</span><span>{money(total)}</span></div><div className="my-5 border-t border-white/10"/><div className="flex items-end justify-between"><span className="font-bold">Total</span><strong className="text-2xl">{money(total)}</strong></div><Link href="/checkout" className="mt-6 block w-full rounded-xl bg-violet-600 py-3.5 text-center font-bold purple-shadow">Finalizar compra</Link><button onClick={clearCart} className="mt-3 w-full py-2 text-sm text-zinc-500 hover:text-white">Limpar carrinho</button><p className="mt-4 text-center text-xs leading-5 text-zinc-600">Pagamento via Pix com envio de comprovante.</p></aside></div>:<div className="mt-8 grid min-h-[360px] place-items-center rounded-3xl border border-dashed border-white/15 text-center"><div><div className="text-4xl">🛍️</div><h2 className="mt-5 text-2xl font-black">Seu carrinho está vazio</h2><p className="mt-2 text-zinc-500">Adicione produtos para montar seu pedido.</p><Link href="/produtos" className="mt-6 inline-block rounded-xl bg-violet-600 px-5 py-3 font-bold">Explorar produtos</Link></div></div>}</main>;
}
