import Link from "next/link";
import { createAdminClient } from "@/lib/supabase/admin";
import { orderStatus } from "@/lib/order-status";

export default async function AdminOrdersPage(){
  const {data:orders}=await createAdminClient().from("orders").select("id,order_code,status,total,game_nickname,created_at,profiles(nickname)").order("created_at",{ascending:false});
  return <main className="min-h-screen bg-[#080812] p-6 text-white"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-violet-400">Painel administrativo</p><h1 className="mt-2 text-3xl font-black">Pedidos</h1></div><Link href="/admin" className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold">Voltar</Link></div><div className="mt-8 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-white/5 text-zinc-400"><tr><th className="p-4">Pedido</th><th className="p-4">Cliente</th><th className="p-4">Nickname</th><th className="p-4">Total</th><th className="p-4">Situação</th><th className="p-4"></th></tr></thead><tbody>{orders?.map(order=>{const status=orderStatus[order.status]??{label:order.status,className:""};const profile=Array.isArray(order.profiles)?order.profiles[0]:order.profiles;return <tr key={order.id} className="border-t border-white/10"><td className="p-4 font-bold">{order.order_code}<span className="mt-1 block text-xs font-normal text-zinc-500">{new Date(order.created_at).toLocaleString("pt-BR")}</span></td><td className="p-4">{profile?.nickname??"Cliente"}</td><td className="p-4">{order.game_nickname}</td><td className="p-4 font-bold">{Number(order.total).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${status.className}`}>{status.label}</span></td><td className="p-4"><Link href={`/admin/pedidos/${order.id}`} className="font-bold text-violet-300">Abrir →</Link></td></tr>})}</tbody></table></div></div></main>;
}

