import Link from "next/link";
import { notFound } from "next/navigation";
import OrderChat from "@/app/pedidos/[id]/OrderChat";
import { orderStatus } from "@/lib/order-status";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { updateOrderChat, updateOrderStatus } from "../actions";

type AuditEvent = { id:string; admin_id:string; action:string; details:Record<string,unknown>|null; created_at:string };
type Delivery = { id:string; channel:string; status:string; error_message:string|null; created_at:string };
const actionLabels:Record<string,string>={"status:paid":"Pagamento confirmado","status:proof_rejected":"Comprovante recusado","status:cancelled":"Pedido cancelado","status:delivered":"Pedido marcado como entregue","chat:open":"Atendimento reaberto","chat:close":"Atendimento encerrado"};

export default async function AdminOrderPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params; const admin=createAdminClient();
  const {data:order}=await admin.from("orders").select("*,order_items(product_name,unit_price,quantity),profiles(nickname)").eq("id",id).maybeSingle(); if(!order)notFound();
  const {data:{user}}=await (await createClient()).auth.getUser(); if(!user)notFound();
  const [{data:messages},{data:events},{data:deliveries}]=await Promise.all([
    admin.from("order_messages").select("id,user_id,message,created_at,profiles(nickname,avatar_url)").eq("order_id",id).order("created_at"),
    admin.from("order_admin_events").select("id,admin_id,action,details,created_at").eq("order_id",id).order("created_at",{ascending:false}),
    admin.from("notification_deliveries").select("id,channel,status,error_message,created_at").eq("link",`/pedidos/${id}`).order("created_at",{ascending:false}).limit(20)
  ]);
  const adminIds=[...new Set(((events??[]) as AuditEvent[]).map(event=>event.admin_id))];
  const {data:adminProfiles}=adminIds.length?await admin.from("profiles").select("id,nickname").in("id",adminIds):{data:[]};
  const adminNames=new Map((adminProfiles??[]).map(profile=>[profile.id,profile.nickname]));
  let proofUrl:string|null=null;if(order.proof_path){const {data}=await admin.storage.from("payment-proofs").createSignedUrl(order.proof_path,600);proofUrl=data?.signedUrl??null;}
  const status=orderStatus[order.status]??{label:order.status,className:""}; const chatAvailable=["paid","preparing_delivery","delivered"].includes(order.status); const canSend=chatAvailable&&!order.chat_closed_at;
  const buttons:string[][]=order.status==="proof_submitted"||order.status==="under_review"?[["paid","Confirmar pagamento"],["proof_rejected","Recusar comprovante"],["cancelled","Cancelar pedido"]]:order.status==="paid"||order.status==="preparing_delivery"?[["delivered","Marcar como entregue"],["cancelled","Cancelar pedido"]]:order.status==="awaiting_payment"||order.status==="proof_rejected"?[["cancelled","Cancelar pedido"]]:[];
  return <main className="min-h-screen bg-[#080812] px-4 py-6 text-white sm:p-6"><div className="mx-auto max-w-4xl">
    <Link href="/admin/pedidos" className="inline-flex min-h-11 items-center text-sm font-bold text-zinc-300">← Todos os pedidos</Link>
    <div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-violet-400">Pedido</p><h1 className="break-all text-2xl font-black sm:text-3xl">{order.order_code}</h1><p className="mt-2 text-sm text-zinc-300">Cliente: {order.profiles?.nickname??"Cliente"} • Nick: {order.game_nickname}</p>{order.delivery_due_at&&!["delivered","cancelled"].includes(order.status)&&<p className="mt-1 text-sm text-amber-300">Prazo: {new Date(order.delivery_due_at).toLocaleString("pt-BR")}</p>}</div><span className={`rounded-full px-4 py-2 text-sm font-bold ${status.className}`}>{status.label}</span></div>
    <section className="mt-7 rounded-2xl border border-white/10 bg-[#111122] p-4 sm:p-6"><div className="space-y-3">{order.order_items?.map((item:{product_name:string;unit_price:number;quantity:number},index:number)=><div key={index} className="flex justify-between gap-4"><span>{item.quantity}× {item.product_name}</span><strong className="shrink-0">{(Number(item.unit_price)*item.quantity).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</strong></div>)}</div><div className="my-5 border-t border-white/10"/><div className="flex justify-between text-xl"><strong>Total</strong><strong>{Number(order.total).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</strong></div>{proofUrl&&<a href={proofUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-sky-600 px-5 font-bold">Abrir comprovante</a>}</section>
    {buttons.length>0&&<section className="mt-6 rounded-2xl border border-white/10 bg-[#111122] p-4 sm:p-6"><h2 className="font-black">Atualizar pedido</h2><div className="mt-4 flex flex-wrap gap-2">{buttons.filter(([value])=>value!=="proof_rejected").map(([value,label])=><form key={value} action={updateOrderStatus}><input type="hidden" name="order_id" value={id}/><input type="hidden" name="status" value={value}/><button className={`min-h-11 rounded-xl px-4 py-2 text-sm font-bold ${value==="paid"||value==="delivered"?"bg-emerald-600":"bg-red-600"}`}>{label}</button></form>)}</div>{buttons.some(([value])=>value==="proof_rejected")&&<form action={updateOrderStatus} className="mt-5 rounded-xl border border-red-500/20 bg-red-500/5 p-4"><input type="hidden" name="order_id" value={id}/><input type="hidden" name="status" value="proof_rejected"/><label htmlFor="rejection_reason" className="text-sm font-bold text-red-200">Motivo da recusa</label><textarea id="rejection_reason" name="rejection_reason" required minLength={5} maxLength={300} placeholder="Ex.: imagem ilegível ou valor diferente." className="mt-2 min-h-24 w-full rounded-xl border border-white/10 bg-[#080812] p-3 text-base outline-none focus:border-red-400"/><button className="mt-3 min-h-11 rounded-xl bg-red-600 px-4 py-2 text-sm font-bold">Recusar comprovante</button></form>}</section>}
    {chatAvailable&&<><section className="mt-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 bg-[#111122] p-5"><div><h2 className="font-black">Atendimento do pedido</h2><p className="mt-1 text-sm text-zinc-400">{canSend?"Chat aberto para a equipe e o cliente.":"Chat encerrado; o histórico segue visível."}</p></div><form action={updateOrderChat}><input type="hidden" name="order_id" value={id}/><input type="hidden" name="chat_action" value={canSend?"close":"open"}/><button className={`min-h-11 rounded-xl px-4 py-2 text-sm font-bold ${canSend?"bg-zinc-700":"bg-violet-600"}`}>{canSend?"Encerrar atendimento":"Reabrir atendimento"}</button></form></section><OrderChat orderId={id} userId={user.id} initialMessages={(messages??[]) as never[]} canSend={canSend}/></>}
    <div className="mt-6 grid gap-6 lg:grid-cols-2">
      <section className="rounded-2xl border border-white/10 bg-[#111122] p-5"><h2 className="font-black">Histórico administrativo</h2><div className="mt-4 space-y-3">{(events as AuditEvent[]|null)?.length?(events as AuditEvent[]).map(event=><div key={event.id} className="border-l-2 border-violet-500/50 pl-3"><p className="text-sm font-bold">{actionLabels[event.action]??event.action}</p><p className="mt-1 text-xs text-zinc-400">{adminNames.get(event.admin_id)??"Administrador"} • {new Date(event.created_at).toLocaleString("pt-BR")}</p>{typeof event.details?.rejection_reason==="string"&&<p className="mt-1 text-xs text-red-200">{event.details.rejection_reason}</p>}</div>):<p className="text-sm text-zinc-400">Nenhuma alteração registrada ainda.</p>}</div></section>
      <section className="rounded-2xl border border-white/10 bg-[#111122] p-5"><h2 className="font-black">Entrega de avisos</h2><div className="mt-4 space-y-3">{(deliveries as Delivery[]|null)?.length?(deliveries as Delivery[]).map(delivery=><div key={delivery.id} className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold capitalize">{delivery.channel==="site"?"Notificação no site":delivery.channel}</p><p className="text-xs text-zinc-400">{new Date(delivery.created_at).toLocaleString("pt-BR")}</p>{delivery.error_message&&<p className="mt-1 line-clamp-2 text-xs text-red-300" title={delivery.error_message}>{delivery.error_message}</p>}</div><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${delivery.status==="sent"?"bg-emerald-500/15 text-emerald-300":"bg-red-500/15 text-red-300"}`}>{delivery.status==="sent"?"Enviado":"Falhou"}</span></div>):<p className="text-sm text-zinc-400">Nenhum aviso registrado ainda.</p>}</div></section>
    </div>
  </div></main>;
}
