import LegalPage from "@/app/components/LegalPage";

export default function RefundPage(){return <LegalPage eyebrow="Compras e entregas" title="Política de Reembolso" intro="Nosso objetivo é entregar cada pedido com clareza e segurança. Esta política descreve quando um pedido pode ser cancelado ou reembolsado, sem afastar os direitos previstos na legislação brasileira.">
  <section><h2>1. Prazo de entrega garantido</h2><p>A entrega será realizada em até 24 horas contadas da confirmação manual do pagamento. Se esse prazo terminar sem entrega por responsabilidade da Cosmic Store, o pedido se tornará automaticamente elegível ao reembolso integral.</p><p>A elegibilidade automática não significa movimentação bancária instantânea: a equipe confirmará os dados necessários e processará a devolução pelo meio disponível. O prazo de crédito após o processamento pode depender da instituição financeira.</p></section>
  <section><h2>2. Quando o reembolso integral é devido</h2><ul><li>Produto indisponível depois da confirmação do pagamento.</li><li>Impossibilidade de entrega atribuível à Cosmic Store.</li><li>Entrega não concluída no prazo de 24 horas, salvo impedimento causado pelo cliente ou evento externo devidamente informado.</li><li>Pagamento confirmado em duplicidade.</li><li>Outras situações exigidas pela legislação aplicável.</li></ul></section>
  <section><h2>3. Impedimentos causados pelo cliente ou por terceiros</h2><p>O prazo poderá ser suspenso quando o nickname estiver incorreto, a conta não puder receber o item, o cliente não responder a uma solicitação indispensável, a plataforma do jogo estiver indisponível ou houver bloqueio externo. A equipe solicitará a correção pelo chat. Se a entrega continuar impossível, será analisada a solução adequada, inclusive reembolso quando aplicável.</p></section>
  <section><h2>4. Produto já entregue</h2><p>Após a entrega efetiva de um produto digital, pedidos de cancelamento serão analisados conforme a natureza do item, a possibilidade técnica de reversão e os direitos previstos no Código de Defesa do Consumidor. Esta política não pretende restringir garantias legais.</p></section>
  <section><h2>5. Comprovante recusado</h2><p>A recusa do comprovante não representa perda automática do pedido. O cliente verá o motivo e poderá enviar um novo arquivo. Não haverá entrega enquanto o pagamento não puder ser confirmado no banco.</p></section>
  <section><h2>6. Como solicitar</h2><p>Acesse o pedido e fale pelo chat quando disponível ou utilize o canal de suporte indicado no site. Informe o código do pedido e os dados necessários para localizar o pagamento. Nunca envie senha bancária ou senha da conta do jogo.</p></section>
  <section><h2>7. Forma do reembolso</h2><p>Quando aprovado, o reembolso será preferencialmente enviado ao titular e pelo meio compatível com o pagamento original. Poderemos solicitar uma chave Pix ou dado equivalente apenas quando necessário para realizar a devolução com segurança.</p></section>
</LegalPage>}
