import LegalPage from "@/app/components/LegalPage";

export default function PrivacyPage(){return <LegalPage eyebrow="Seus dados" title="Política de Privacidade" intro="A Cosmic Store utiliza apenas os dados necessários para manter contas, processar pedidos, prestar suporte, prevenir fraudes e cumprir obrigações legais. Esta política segue os princípios de finalidade, necessidade, transparência e segurança da LGPD.">
  <section><h2>1. Dados que tratamos</h2><ul><li>Conta: e-mail, nickname, identificador e avatar do Discord quando utilizado.</li><li>Pedido: produtos, valores, nickname no jogo, situação e histórico de atendimento.</li><li>Pagamento: comprovante enviado pelo cliente e informações necessárias à conferência manual. Não armazenamos senha bancária.</li><li>Comunicação: mensagens, notificações, feedbacks e denúncias no chat.</li><li>Dados técnicos: registros essenciais de acesso, segurança e funcionamento disponibilizados pelos provedores.</li></ul></section>
  <section><h2>2. Por que utilizamos os dados</h2><p>Tratamos os dados para executar a compra e a entrega, autenticar usuários, responder solicitações, enviar avisos do pedido, proteger a loja contra abuso e fraude, manter registros necessários e cumprir obrigações legais ou regulatórias.</p></section>
  <section><h2>3. Serviços utilizados</h2><p>Dados podem ser processados por fornecedores necessários ao funcionamento da loja, incluindo Supabase (banco, autenticação e arquivos), Netlify (hospedagem), Resend (e-mails) e Discord (login e mensagens). Cada fornecedor também aplica suas próprias práticas de segurança e privacidade. O uso desses serviços pode envolver processamento em outros países, com salvaguardas aplicáveis.</p></section>
  <section><h2>4. Compartilhamento</h2><p>Não vendemos dados pessoais. Compartilhamos somente o necessário com prestadores de serviço, autoridades quando houver obrigação legal ou profissionais envolvidos na defesa de direitos. Feedbacks publicados exibem o nickname, a avaliação e o comentário; o cliente pode solicitar análise ou remoção.</p></section>
  <section><h2>5. Conservação e segurança</h2><p>Os dados são mantidos pelo tempo necessário para entregar produtos, prestar suporte, prevenir fraude, cumprir obrigações e exercer direitos. Comprovantes e registros podem ser eliminados ou anonimizados quando deixarem de ser necessários, respeitados os prazos legais. Aplicamos controle de acesso, conexões protegidas e regras de banco de dados, embora nenhum sistema seja totalmente imune a incidentes.</p></section>
  <section><h2>6. Direitos do titular</h2><p>O titular pode solicitar confirmação e acesso, correção, informação sobre compartilhamento, anonimização, bloqueio ou eliminação quando cabível, portabilidade nos limites técnicos, revisão de decisões automatizadas e revogação de consentimento. Alguns registros poderão ser preservados quando houver obrigação legal, prevenção de fraude ou exercício regular de direitos.</p></section>
  <section><h2>7. Cookies e sessão</h2><p>Utilizamos cookies e armazenamento local essenciais para login, segurança e carrinho. Sem esses recursos, partes importantes do site podem não funcionar. Ferramentas não essenciais, se adicionadas futuramente, deverão receber informação adequada.</p></section>
  <section><h2>8. Como exercer seus direitos</h2><p>Utilize os canais de contato exibidos no site e informe qual direito deseja exercer. Poderemos solicitar confirmação de identidade para impedir acesso indevido aos dados de outra pessoa.</p></section>
</LegalPage>}
